repos:
-   repo: https://github.com/ikamensh/flynt/
    rev: '1.0.1'
    hooks:
    -   id: flynt
-   repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
    - id: isort
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.1.6'
    hooks:
    - id: ruff
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://github.com/keewis/blackdoc
    rev: v0.3.9
    hooks:
    - id: blackdoc
      language_version: python3.9
